Repository canonical-web-and-design/practices, pull requests merged in 2018-11, with the labels that each got.

#98 Make into a Jekyll site
  .gitignore
  CONTRIBUTING.md
  README.md
  _config.yml
  _layouts/base.html
  coding/browser-support.md
  coding/code-formatting.md
  coding/html.md
  coding/javascript.md
  coding/react.md
  coding/stylesheets.md
  content/copy-reviews.md
  content/filenames.md
  css/styles.css
  design/vanilla-design-specs.md
  foosball.md
  index.md
  local-development/ports.md
  local-development/the-run-script.md
  podcasts.md
  project-management/fibonacci-estimation-guide.md
  project-management/stand-ups.md
  project-management/zenhub.md
  solutions/documentation.md
  workflow/deploy.md
  workflow/github.md
  workflow/labels.md
  workflow/qa-steps.md
Labels: Review: Code +1, Review: QA +1

#114 Change title to "Web and design team practices"; Use the Canonical logo
  CONTRIBUTING.md
  README.md
  _layouts/base.html
  foosball.md
  index.md
Labels: Code, Content

#113 Use the logo and title as a home link
  _layouts/base.html
Labels: Code, Review: Code +1, Review: QA +1

#116 Add active class to current page in sidebar nav
  _layouts/base.html
Labels: Review: Code +1, Review: QA +1

#124 Automate navigation in website
  _config.yml
  _layouts/base.html
  _layouts/default.html
  coding/browser-support.md
  coding/html.md
  coding/javascript.md
  coding/python.md
  coding/stylesheets.md
  content/copy-reviews.md
  content/filenames.md
  design/vanilla-design-specs.md
  index.html
  index.md
  miscellaneous/foosball.md
  miscellaneous/podcasts.md
  project-management/fibonacci-estimation-guide.md
  project-management/stand-ups.md
  project-management/zenhub.md
  project-structure/documentation.md
  project-structure/general-structure.md
  project-structure/ports.md
  project-structure/project-philosophy.md
  project-structure/server-side-frameworks.md
  project-structure/the-run-script.md
  workflow/deploy.md
  workflow/github.md
  workflow/labels.md
  workflow/qa-steps.md
Labels: Review: Code +1, Review: QA +1
