Repository canonical-web-and-design/practices, pull requests merged in 2019-07, with the labels that each got.

#188 Update badges
  README.md
Labels: Review: Code +1, Review: QA +1

#190 Update PR merge best practices
  workflow/github.md
Labels: Review: Code needed

#179 Add a supplementary note on code comments
  coding/javascript.md
Labels: Review: Code needed

#194 Add new port for dqlite.io repository
  project-structure/ports.md
Labels: Review: QA +1
