Repository canonical-web-and-design/practices, pull requests merged in 2019-02, with the labels that each got.

#171 Explain licenses in README
  README.md
Labels: Review: Code +1

#167 Add Prettier ✨
  .prettierignore
  CONTRIBUTING.md
  README.md
  _config.yml
  coding/browser-support.md
  coding/html.md
  coding/javascript.md
  coding/review.md
  coding/stylesheets.md
  content/copy-reviews.md
  content/filenames.md
  css/styles.css
  design/vanilla-design-specs.md
  miscellaneous/foosball.md
  miscellaneous/podcasts.md
  project-management/fibonacci-estimation-guide.md
  project-management/zenhub.md
  project-structure/documentation.md
  project-structure/ports.md
  project-structure/project-philosophy.md
  project-structure/server-side-frameworks.md
  project-structure/the-run-script.md
  workflow/deploy.md
  workflow/github.md
  workflow/labels.md
  yarn.lock
Labels: Review: Code needed

#172 Fix markdown list in copy-review.md
  .editorconfig
  README.md
  content/copy-reviews.md
  project-management/iteration-creation.md
Labels: Review: Code +1, Review: QA +1

#170 Add circleci step to run Prettier
  .circleci/config.yml
  .gitignore
  package.json
  yarn.lock
Labels: Review: Code needed
